### ISSUE TITLE
Game Crash after dying and then re-spawning

### ISSUE THREAD

**Issue by stormbringerGT** [Electroblob77/Wizardry#160]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2] 
Wizardry version: 4.1.4 
Environment: Singleplayer

Issue details: Died to a mob in a dungeon and when I clicked re-spawn (of which my bed was very close) the game crashed throwing up this error. Since then upon loading in the game will continually crash upon loading.

Other mods involved: Special Mobs https://www.curseforge.com/minecraft/mc-mods/special-mobs

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.22.1-build.0389.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.156.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (AdPother-1.12.2-1.0.21.1-build.0389.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LogisticsPipesCoreLoader (logisticspipes-0.10.2.203.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.2.2.jar)
  Quark Plugin (Quark-r1.5-168.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.5.4.0-build.0384.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/29/19 2:35 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at electroblob.wizardry.item.IConjuredItem.onLivingDropsEvent(IConjuredItem.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_603_IConjuredItem_onLivingDropsEvent_LivingDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:510)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityCaveSpider.func_70652_k(SourceFile:38)
	at fathertoast.specialmobs.entity.cavespider.Entity_SpecialCaveSpider.func_70652_k(Entity_SpecialCaveSpider.java:153)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at fathertoast.specialmobs.entity.cavespider.Entity_SpecialCaveSpider.func_70636_d(Entity_SpecialCaveSpider.java:144)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(EntitySpider.java:85)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at electroblob.wizardry.item.IConjuredItem.onLivingDropsEvent(IConjuredItem.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_603_IConjuredItem_onLivingDropsEvent_LivingDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:510)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityCaveSpider.func_70652_k(SourceFile:38)
	at fathertoast.specialmobs.entity.cavespider.Entity_SpecialCaveSpider.func_70652_k(Entity_SpecialCaveSpider.java:153)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at fathertoast.specialmobs.entity.cavespider.Entity_SpecialCaveSpider.func_70636_d(Entity_SpecialCaveSpider.java:144)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(EntitySpider.java:85)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: specialmobs:specialcavespider (fathertoast.specialmobs.entity.cavespider.Entity_SpecialCaveSpider)
	Entity ID: 436869
	Entity Name: Cave Spider
	Entity's Exact location: -2508.99, 46.00, -3665.57
	Entity's Block location: World: (-2509,46,-3666), Chunk: (at 3,2,14 in -157,-230; contains blocks -2512,0,-3680 to -2497,255,-3665), Region: (-5,-8; contains chunks -160,-256 to -129,-225, blocks -2560,0,-4096 to -2049,255,-3585)
	Entity's Momentum: 0.00, -0.08, -0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Testing
	All players: 1 total; [EntityPlayerMP['StormbringerGTX'/387573, l='Testing', x=-2508.30, y=46.00, z=-3665.70]]
	Chunk stats: ServerChunkCache: 1514 Drop: 0
	Level seed: -1817577923448677370
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"random","rainScheme":"random","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (177,64,258), Chunk: (at 1,4,2 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 103432 game time, 144406 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 129960 (now: false), thunder time: 17675 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2310189744 bytes (2203 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 5, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 223 mods loaded, 223 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by Electroblob77** [comment]
Looks like the special mobs cave spider has attempted to drop an invalid item. Unfortunately, it's not open-source so there's not much I can find out beyond that. Mobs should not be dropping null `EntityItem`s, nor should any `ItemStack` be null.

**Comment by stormbringerGT** [comment]
Anyway I can help you with more info? Wasn't even sure if your mod was the core issue, or to be a side effect of special mobs doing something funky.

**Comment by Electroblob77** [comment]
Oh it's easy enough to protect against the crash in wizardry's code, but as far as I can tell it's an issue on special mobs' end so it may be worth posting it there too.

**Comment by stormbringerGT** [comment]
Will do, thanks for the heads up!
