### ISSUE TITLE
Crash to title screen

### ISSUE THREAD

**Issue by MohawkyMagoo** [Electroblob77/Wizardry#169]
java.lang.NullPointerException
    at electroblob.wizardry.potion.ISyncedPotion.onPotionRemoveEvent(ISyncedPotion.java:70)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_ISyncedPotion_onPotionRemoveEvent_PotionRemoveEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.entity.EntityLivingBase.removePotionEffect(EntityLivingBase.java:792)
    at de.teamlapen.vampirism.player.vampire.VampirePlayer.endFeeding(VampirePlayer.java:318)
    at de.teamlapen.vampirism.player.vampire.VampirePlayer.onEntityAttacked(VampirePlayer.java:558)
    at de.teamlapen.lib.entity.EntityEventHandler.onLivingAttack(EntityEventHandler.java:58)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1183_EntityEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onPlayerAttack(ForgeHooks.java:585)
    at net.minecraft.entity.player.EntityPlayer.attackEntityFrom(EntityPlayer.java:994)
    at net.minecraft.entity.player.EntityPlayerMP.attackEntityFrom(EntityPlayerMP.java:645)
    at net.minecraft.entity.monster.EntityMob.attackEntityAsMob(EntityMob.java:99)
    at net.minecraft.entity.monster.EntityWitherSkeleton.attackEntityAsMob(SourceFile:104)
    at net.minecraft.entity.ai.EntityAIAttackMelee.checkAndPerformAttack(EntityAIAttackMelee.java:178)
    at net.minecraft.entity.ai.EntityAIAttackMelee.updateTask(EntityAIAttackMelee.java:167)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:45)
    at net.minecraft.entity.monster.AbstractSkeleton.onLivingUpdate(AbstractSkeleton.java:144)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
    at electroblob.wizardry.entity.living.EntityWitherSkeletonMinion.onUpdate(EntityWitherSkeletonMinion.java:112)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbc000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: ebwizardry:wither_skeleton_minion (electroblob.wizardry.entity.living.EntityWitherSkeletonMinion)
  Entity ID: 79545
  Entity Name: Wither Skeleton
  Entity's Exact location: -2133.53, 70.00, -1796.30
  Entity's Block location: World: (-2134,70,-1797), Chunk: (at 10,4,11 in -134,-113; contains blocks -2144,0,-1808 to -2129,255,-1793), Region: (-5,-4; contains chunks -160,-128 to -129,-97, blocks -2560,0,-2048 to -2049,255,-1537)
  Entity's Momentum: 0.00, -0.08, -0.02
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,ForgeData:{"Potion Core - Health Fix":20.0f,"Potion Core - Jump Boost Updated":1b},Attributes:[{Base:1.0d,Name:"potioncore.projectileDamage"},{Base:1.0d,Name:"potioncore.magicDamage"},{Base:1.0d,Name:"potioncore.jumpHeight"},{Base:1.0d,Name:"potioncore.damageResistance"},{Base:0.0d,Name:"potioncore.magicShielding"},{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.25d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Modifiers:[{UUIDMost:-4498169829461111243L,UUIDLeast:-8419631031275058799L,Amount:-0.005892803588055098d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:2.0d,Name:"generic.attackDamage"}],lifetime:0,Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,ForgeCaps:{"dsurround:data":{a:0b,f:0b},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"multimob:summonable":{SummonerUUID:"",Following:0b,TimeLimit:1000},"ancientwarfarestructure:respawn_data":{},"vampirism:iextendedcreature":{maxBlood:-1,poisonousBlood:0b,bloodLevel:-1}},HandDropChances:[0.0f,0.085f],PersistenceRequired:0b,Motion:[0.0d,-0.0784000015258789d,-0.015414987032303677d],Leashed:0b,UUIDLeast:-8541509140501754049L,Health:20.0f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[180.23247f,6.895495f],UpdateBlocked:0b,HandItems:[{id:"minecraft:stone_sword",Count:1b,Damage:0s},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:498359598231011684L,Pos:[-2133.5285514968928d,70.0d,-1796.3011026703666d],Fire:0s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}

**Comment by MohawkyMagoo** [comment]
Seems like a clash between EB and Vampirism mods? Single player game, a vampire hunter camp had spawned a little way from an EB new structure

**Comment by Yldales** [comment]
Hi,

I've go the same error/client crash ( _java.lang.NullPointerException: Ticking entity at electroblob.wizardry.potion.ISyncedPotion.onPotionRemoveEvent_ ) in singleplayer, after using Alt+Tab to return to the game window.

**Forge:** 14.23.5.2838
**Electroblob's Wizardry:** 4.2.0
**Optifine:** 1.12.2_HD_U_E3

**Crash report:** https://pastebin.com/raw/xzH9RSjn

**Comment by Electroblob77** [comment]
Duplicate of #166, this is a conflict with PotionCore.
