### ISSUE TITLE
Error Trying to Load an EventBusSubscriber

### ISSUE THREAD

**Issue by theandrewdonovan** [Electroblob77/Wizardry#231]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer

Issue details: Trying to launch this mod for the first time using MultiMC Launcher. I get the below error:

[main/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber electroblob.wizardry.spell.Transience for modid ebwizardry
java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/PotionEvent$PotionAddedEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_222]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_222]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_222]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_222]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
...
...
and so on

Other mods involved: Baubles, Antique Atlas. These are the only mods I'm using

Link to crash report (if applicable): https://pastebin.com/JkTnnC10

**Comment by Electroblob77** [comment]
Update your forge to version 14.23.5.2814 or newer.
