### ISSUE TITLE
Crash with Epic siege mod?

### ISSUE THREAD

**Issue by Jaderey** [Electroblob77/Wizardry#236]
```
Time: 2019-09-03 20:18:06 CDT
Description: Ticking player

java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.entity.living.LivingSetAttackTargetEvent
    at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:96)
    at electroblob.wizardry.spell.Possession.onLivingSetAttackTargetEvent(Possession.java:627)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_372_Possession_onLivingSetAttackTargetEvent_LivingSetAttackTargetEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:575)
    at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.entity.EntityLiving.setAttackTarget(EntityLiving.java:218)
    at funwayguy.epicsiegemod.ai.ESM_EntityAINearestAttackableTarget.startExecuting(ESM_EntityAINearestAttackableTarget.java:97)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:102)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:885)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at gaia.entity.EntityMobAssist.onLivingUpdate(EntityMobAssist.java:43)
    at gaia.entity.monster.EntityGaiaValkyrie.onLivingUpdate(EntityGaiaValkyrie.java:218)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at gaia.entity.EntityMobAssist.onUpdate(EntityMobAssist.java:51)
    at electroblob.wizardry.spell.Possession.onPlayerTickEvent(Possession.java:471)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_Possession_onPlayerTickEvent_PlayerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:190)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

```

I was messing around with the Possession spell and got some errors in combination with some mods. 

I'm not entirely sure this is the only reason i'm crashing (not related to this mod anyways) but its the first one to pop up so thought id let you know.
although from what i'm reading i think its an issue with epic siege mod and this one.

I'm a bit new to Github so sorry for any formatting mistakes.

**Comment by Electroblob77** [comment]
No other mods to blame in this case, that's entirely my fault. Will fix for the next patch, thanks for reporting.
