### ISSUE TITLE
Error with Wizard NBT saving

### ISSUE THREAD

**Issue by Darkere** [Electroblob77/Wizardry#291]
This error message is repeated in the server log:

```[00:06:24] [Server thread/ERROR] [ebwizardry]: Error when reading list from NBT: unexpected tag type LONG
java.lang.ClassCastException: net.minecraft.nbt.NBTTagLong cannot be cast to net.minecraft.nbt.NBTTagCompound
	at electroblob.wizardry.util.NBTExtras.NBTToList(NBTExtras.java:183) [NBTExtras.class:?]
	at electroblob.wizardry.entity.living.EntityWizard.func_70037_a(EntityWizard.java:419) [EntityWizard.class:?]
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1866) [vg.class:?]
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:221) [vi.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:602) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:529) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

Minecraft version: 1.12.2
Wizardry version: 4.2.3
Environment: Server 
Other mods involved: Pack ATM3- Remix

**Comment by Electroblob77** [comment]
Are you playing in a world created with an older version of wizardry? If so, this is because of a change to the NBT format for how wizards keep track of which blocks are part of their tower in version 4.2. The only effect in-game should be that wizards with the old format will not get angry when you break their tower. I agree the server log is annoying though, I can fix this for the next patch.
