### ISSUE TITLE
Crash (random)

### ISSUE THREAD

**Issue by MohawkyMagoo** [Electroblob77/Wizardry#305]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.5 [change as necessary]
Environment: Singleplayer

Issue details: Opened Voxalmap minimap

java.lang.NullPointerException
    at electroblob.wizardry.client.renderer.RenderArcaneLock.onRenderWorldLastEvent(RenderArcaneLock.java:66)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_32_RenderArcaneLock_onRenderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1432)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Electroblob77** [comment]
Okay, VoxelMap seems to have somehow made null tile entities when rendering its map. I'll add a check which should fix this.
