### ISSUE TITLE
Ice Spikes spell doesn't seem to do anything

### ISSUE THREAD

**Issue by belathus** [Electroblob77/Wizardry#306]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Server

Issue details: Casting "Ice Spikes" doesn't seem to do anything, as the title states. I recall it creating a floor of spikes in a previous version, but right now, when I cast it, the spell goes on cooldown, uses no mana, and no effect appears.

It was mentioned in #287, though I figured I'd make this its own issue.

Other mods involved: N/A

Link to crash report (if applicable): N/A, though an error does appear on the server's log:

```[15:36:08] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_72-internal]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
        at electroblob.wizardry.entity.construct.EntityIceSpike.setFacing(EntityIceSpike.java:34) ~[EntityIceSpike.class:?]
        at electroblob.wizardry.spell.IceSpikes.addConstructExtras(IceSpikes.java:72) ~[IceSpikes.class:?]
        at electroblob.wizardry.spell.IceSpikes.addConstructExtras(IceSpikes.java:13) ~[IceSpikes.class:?]
        at electroblob.wizardry.spell.SpellConstruct.spawnConstruct(SpellConstruct.java:163) ~[SpellConstruct.class:?]
        at electroblob.wizardry.spell.IceSpikes.spawnConstruct(IceSpikes.java:38) ~[IceSpikes.class:?]
        at electroblob.wizardry.spell.SpellConstructRanged.cast(SpellConstructRanged.java:102) ~[SpellConstructRanged.class:?]
        at electroblob.wizardry.item.ItemWand.cast(ItemWand.java:423) ~[ItemWand.class:?]
        at electroblob.wizardry.item.ItemWand.onItemRightClick(ItemWand.java:353) ~[ItemWand.class:?]
        at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:358) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:765) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9) ~[mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_72-internal]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more
```

**Comment by Electroblob77** [comment]
Okay yep, that's another one of those client-side-only-for-no-reason methods. Will fix for the next patch.
