### ISSUE TITLE
Thorns Forest magic will take players offline

### ISSUE THREAD

**Issue by 1954362979** [Electroblob77/Wizardry#354]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.2.8 
Environment: Server 

Issue details: Thorns Forest Magic will cause dead players to disconnect after resurrection and require players to log in to the server again
问题详细信息：[描述问题发生时的操作，出了什么问题，预期会发生什么，等等。]
Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): 
[01:41:54] [Server thread/ERROR]: Failed to create block entity ebwizardry:player_save_timed
java.lang.InstantiationException: electroblob.wizardry.tileentity.TileEntityPlayerSaveTimed
at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_121]
at net.minecraft.tileentity.TileEntity.create(TileEntity.java:112) [avj.class:?]
at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:47) [CraftBlockEntityState.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) [CraftBlockEntityState.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:380) [CraftBlock.class:git-CatServerAsync-1.12.2-2d6b7c1]
at com.lishid.openinv.internal.v1_12_R1.AnySilentContainer.isAnySilentContainer(AnySilentContainer.java:70) [OpenInv.jar:?]
at com.lishid.openinv.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:60) [OpenInv.jar:?]
at catserver.server.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) [?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) [EventExecutor$2.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:504) [SimplePluginManager.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:489) [SimplePluginManager.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274) [CraftEventFactory.class:git-CatServerAsync-1.12.2-2d6b7c1]
at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:495) [or.class:?]
at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1128) [pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) [ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) [ma.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:473) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:779) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: electroblob.wizardry.tileentity.TileEntityPlayerSaveTimed.<init>()
at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_121]
... 26 more
[01:41:54] [Server thread/ERROR]: A TileEntity ebwizardry:player_save_timed(electroblob.wizardry.tileentity.TileEntityPlayerSaveTimed) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.InstantiationException: electroblob.wizardry.tileentity.TileEntityPlayerSaveTimed
at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_121]
at net.minecraft.tileentity.TileEntity.create(TileEntity.java:112) [avj.class:?]
at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:47) [CraftBlockEntityState.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:26) [CraftBlockEntityState.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:380) [CraftBlock.class:git-CatServerAsync-1.12.2-2d6b7c1]
at com.lishid.openinv.internal.v1_12_R1.AnySilentContainer.isAnySilentContainer(AnySilentContainer.java:70) [OpenInv.jar:?]
at com.lishid.openinv.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:60) [OpenInv.jar:?]
at catserver.server.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) [?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) [EventExecutor$2.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:504) [SimplePluginManager.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:489) [SimplePluginManager.class:git-CatServerAsync-1.12.2-2d6b7c1]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274) [CraftEventFactory.class:git-CatServerAsync-1.12.2-2d6b7c1]
at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:495) [or.class:?]
at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1128) [pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) [ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) [ma.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:473) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:779) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: electroblob.wizardry.tileentity.TileEntityPlayerSaveTimed.<init>()
at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_121]
... 26 more

**Comment by Electroblob77** [comment]
Okay, just to check I've understood correctly: A player dies in a forest of thorns, is resurrected inside the thorns and then they get disconnected with an error? Should be able to reproduce that and look into it, thanks.

**Comment by 1954362979** [comment]
> Okay, just to check I've understood correctly: A player dies in a forest of thorns, is resurrected inside the thorns and then they get disconnected with an error? Should be able to reproduce that and look into it, thanks.

Players in the server resurrected at home after being killed in the thorn bush will cause disconnection

**Comment by Electroblob77** [comment]
Oh you meant respawned, sorry. I got confused because there's a spell called resurrection 😅

**Comment by 1954362979** [comment]
> Oh you meant respawned, sorry. I got confused because there's a spell called resurrection 😅

My english is not very good

**Comment by Electroblob77** [comment]
I think this probably got fixed as part of the forest of thorns fixes in 4.3. Please reopen this issue if it persists in the newest version.
