### ISSUE TITLE
Crash While Fighting Ice Wizard

### ISSUE THREAD

**Issue by Shibva** [Electroblob77/Wizardry#466]
Ticking entity attack when fighting a Ice Wizard With its Blizzard Beam attack

Jist of the Crash Report:
```
java.lang.NullPointerException: Ticking entity
	at com.favouritedragon.arcaneessentials.common.spell.ice.BlizzardBeam.onEntityHit(BlizzardBeam.java:41)
	at electroblob.wizardry.spell.SpellRay.cast(SpellRay.java:183)
	at electroblob.wizardry.entity.living.EntityAIAttackSpell.attemptCastSpell(EntityAIAttackSpell.java:217)
	at electroblob.wizardry.entity.living.EntityAIAttackSpell.func_75246_d(EntityAIAttackSpell.java:191)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at electroblob.wizardry.entity.living.EntityEvilWizard.func_70636_d(EntityEvilWizard.java:209)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

[crash-2020-06-08_14.36.08-client.txt](https://github.com/Electroblob77/Wizardry/files/4802368/crash-2020-06-08_14.36.08-client.txt)

Version of mod: Electroblob's Wizardry - 4.2.11 - MC 1.12.2 (Latest as of 4/13/2020)
Forge instance: 14.23.5.2847
Addons For Mod are Present along with other mods

Addons Present: 
Arcane essentials
Extra Spells
(3D Wand Re-textures are present via Resource Pack)

All mods and their Versions and system information can be found in the crash report

**__Optifine Is present__** and not caused issues before

**Comment by Tora-B** [comment]
You've attached the wrong crash report, but regardless, this is most likely on Arcane Essentials. There's already an issue report on his tracker about blizzard beam causing crashes: https://github.com/FavouriteDragon/Arcane-Essentials/issues/32

**Comment by Shibva** [comment]
oh, apologies
