### ISSUE TITLE
Fatal Error: Array index out of bounds

### ISSUE THREAD

**Issue by DaggerD711** [Electroblob77/Wizardry#486]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Singleplayer (Custom Mod Pack Testing)

Issue details:Fatal error (array index out of bounds) 

Other mods involved: None that i can tell

Link to crash report (if applicable):

Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(SourceFile:47)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at electroblob.wizardry.client.ClientProxy.handleGlyphDataPacket(ClientProxy.java:571)
	at electroblob.wizardry.packet.PacketGlyphData.lambda$onMessage$0(PacketGlyphData.java:26)
	at electroblob.wizardry.packet.PacketGlyphData$$Lambda$1428/2031765790.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	... 9 more

Im new to minecraft modpacks.

**Comment by LemADEC** [comment]
We need a list of all your mods with their version.
Also, what were you doing at that time?

**Comment by MokahTGS** [comment]
We are getting the same thing.

MC 1.12.2
Forge 14.23.5.2854
Crash log: https://pastebin.com/9neXPTRQ
Full Mod list: https://pastebin.com/PYzmwTnH

This doesn't crash to desktop but it generates a crash log every time I load a new world.  For context, I am trying to load a new world with the Betweenlands as the start location.  Wizardry is set to to world gen in that dimension.

**Comment by Electroblob77** [comment]
Update arcane essentials to the latest (beta) version.
