### ISSUE TITLE
Invisible inventory

### ISSUE THREAD

**Issue by slayerhoodz** [Electroblob77/Wizardry#530]
Minecraft version: 1.12.2
Wizardry version: 4.3
Environment: Singleplayer and Server

Issue details: Unknown cause and seems to occur randomly, the inventory seems to not load in and appears empty, could possibly be related to previous issue? The items are still there and can be interacted with though you can’t see them.

![](https://cdn.discordapp.com/attachments/461653775933767692/769405343661817856/unknown.png)

Other mods involved: none

**Comment by Electroblob77** [comment]
Thanks for posting this here, I suspect it is indeed related to the other issue.

**Comment by Dayyer1** [comment]
I noticed that having Extra Utilities 2's Angel Ring equipped causes this. If you're not familiar with it, all but one of the rings will render wings.
When any of the wings are being rendered, the inventory is invisible. When you have the ring equipped that doesn't do any rendering, everything is fine.
I hope that's clear.

**Comment by jojobmomo** [comment]
Yep if ANYTHING is rendered from other mods (Weapons in npcs hands, arrows, weapons on back) it both causes almost ALL entities to go haywire (Upside down, in false locations) and causes your inventory to go blank. This is most prevalent for me when approaching an ancient warfare castle as the game becomes unplayable (it was in the previous version)

**Comment by Char022** [comment]
I have noticed that opening the Traveller's Knapsack from Tinker's Armory actually does not lead to the issue, even though opening the normal inventory does.

I'll also add that Twilight Forest and Tinker's Construct seem to not trigger this, while other mods do

**Comment by RandomMcSomethin** [comment]
I also got this bug when I was shot by a skeleton and the stuck arrow failed to render.

**Comment by KayCee337** [comment]
I also have been experiencing invisible inventory, accessible when using a chest or backpack, however, otherwise everything disappears, however at random x,y,z levels sometimes it only will show up when looking a specific direction/location sometimes down to the 1/8th of a block when looking anywhere else in any direction it disappears again. Works somewhat okay when near my base (where my bed and everything is) yet the further away I get from there, the worse it gets. Also noticed it renders another entity walking upside down but within my  body frame as well as rendering random upside down non-existing mobs about 3 blocks away from myself (more noticed this when I tried the 3rd person mode)

**Comment by LowderPlay** [comment]
I have successfully reproduced this bug by shooting myself with tipped arrows. This effect goes away when the arrow effect ends. (this is not reproducible by drinking/throwing potions)
![pic1](https://user-images.githubusercontent.com/22765741/97896312-b8d08b80-1d56-11eb-962a-cf5d276e1fa7.png)
![pic2](https://user-images.githubusercontent.com/22765741/97896344-c2f28a00-1d56-11eb-9cb8-9cb093f48a63.png)


```
[Client thread/ERROR] [minecraft/RenderLivingBase]: Couldn't render entity
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.client.renderer.entity.layers.LayerArrow.doRenderLayer(SourceFile:34) ~[cbq.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.renderLayers(RenderLivingBase.java:561) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.doRender(RenderLivingBase.java:270) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:71) [cct.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:28) [cct.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:412) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:392) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.redirect$renderEntityStatic$zbm000(RenderGlobal.java:3753) [buy.class:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:849) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1801) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1614) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1385) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
