### ISSUE TITLE
Crash when using a Betweenlands glider item

### ISSUE THREAD

**Issue by Shibva** [Electroblob77/Wizardry#591]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: for info please see the issue on the other mod conflicting

https://github.com/Angry-Pixel/The-Betweenlands/issues/1150

**Comment by Shibva** [comment]
for simplicity sake, ill post the crashlog here to make it less of a hassle 

https://pastebin.com/VpdLsm6d

**Comment by Shibva** [comment]
and heres the stacktrace

Stacktrace:
	at electroblob.wizardry.client.animation.PlayerAnimator.onRenderPlayerPostEvent(PlayerAnimator.java:234)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_435_PlayerAnimator_onRenderPlayerPostEvent_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:74)
	at thebetweenlands.client.render.entity.RenderVolarkite.onPlayerRenderPre(RenderVolarkite.java:129)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4776_RenderVolarkite_onPlayerRenderPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.doRender(RenderPlayer.java:28)
 
-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 391
	Entity Name: Shibva_
	Entity's Exact location: 1486.80, 140.64, 495.68
	Entity's Block location: World: (1486,140,495), Chunk: (at 14,8,15 in 92,30; contains blocks 1472,0,480 to 1487,255,495), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Entity's Momentum: 0.00, -0.07, 0.00
	Entity's Passengers: []
	Entity's Vehicle: EntityVolarkite['entity.thebetweenlands.volarkite.name'/1276, l='MpServer', x=1486.80, y=140.63, z=495.68]
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:447)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.redirect$zzk000$renderEntityStatic(RenderGlobal.java:3753)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1801)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@4eea4aa
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -231.69449
	Delta: 0.19973397

**Comment by Electroblob77** [comment]
Same crash as #551.
