### ISSUE TITLE
Arcane Bench not working

### ISSUE THREAD

**Issue by duck2lord** [Electroblob77/Wizardry#592]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Singleplayer/LAN game/Server [delete as necessary]

I can place all items on the bench. however when I try to activate it, the animation and sound play, but nothing happens. Spells don't link to the wand, nor does the wand charge. I have RL craft installed but I don't think that's causing the problem, since all of the spell scrolls work fine. 

log events, when I press the a Check
18:41:04.215
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
18:41:04.215
Caused by: java.lang.NoClassDefFoundError: electroblob/wizardry/tileentity/ContainerArcaneWorkbench
18:41:04.215
at codersafterdark.compatskills.common.compats.electroblob.WizardyEventHandler.onSpellBind(WizardyEventHandler.java:21) ~[WizardyEventHandler.class:?]
18:41:04.215
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_922_WizardyEventHandler_onSpellBind_SpellBindEvent.invoke(.dynamic) ~[?:?]
18:41:04.215
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
18:41:04.215
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
18:41:04.215
at electroblob.wizardry.inventory.ContainerArcaneWorkbench.onApplyButtonPressed(ContainerArcaneWorkbench.java:435) ~[ContainerArcaneWorkbench.class:?]
18:41:04.215
at electroblob.wizardry.packet.PacketControlInput.lambda$onMessage$2(PacketControlInput.java:47) ~[PacketControlInput.class:?]
18:41:04.215
at electroblob.wizardry.packet.PacketControlInput$$Lambda$3383/1250065560.run(Unknown Source) ~[?:?]
18:41:04.215
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
18:41:04.215
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
18:41:04.215
at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
18:41:04.215
... 5 more

**Comment by Electroblob77** [comment]
I think this is because CompatSkills is not yet updated for wizardry 4.3+. Try removing CompatSkills or reverting to wizardry 4.2.11.
