### ISSUE TITLE
Game Crashes On Startup

### ISSUE THREAD

**Issue by iSyriux2** [Electroblob77/Wizardry#655]
Minecraft version: 1.12.2 Forge 14.23.5.2855 - 2847
Frequency : Every Time
Annoyance : Catastrophic
Wizardry version: 4.3.1
Issue details: It crashed on start up

![image](https://user-images.githubusercontent.com/62969957/116821043-2d3d8900-ab46-11eb-84e1-27f5a9d1b1f6.png)
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.042210-core.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 5/2/21 12:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: electroblob/wizardry/client/renderer/RenderMagicArrow
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: electroblob/wizardry/client/renderer/RenderMagicArrow
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: electroblob.wizardry.client.renderer.RenderMagicArrow
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 360431776 bytes (343 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version           | Source                                           | Signature                                |
	|:----- |:------------------------ |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2            | minecraft.jar                                    | None                                     |
	| LC    | mcp                      | 9.42              | minecraft.jar                                    | None                                     |
	| LC    | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                    | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | micdoodlecore            |                   | minecraft.jar                                    | None                                     |
	| LC    | obfuscate                | 0.4.2             | minecraft.jar                                    | None                                     |
	| LC    | abyssalcraft             | 1.10.3            | AbyssalCraft-1.12.2-1.10.3.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LC    | aether_legacy            | 1.5.3.2           | aether-1.12.2-v1.5.3.2.jar                       | None                                     |
	| LC    | antiqueatlas             | 4.6.3             | antiqueatlas-1.12.2-4.6.jar                      | None                                     |
	| LC    | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LC    | ebwizardry               | 4.3.1             | ElectroblobsWizardry-4.3.1-MC1.12.2.jar          | None                                     |
	| LC    | ancientspellcraft        | 1.1.3             | ancientspellcraft-1.1.3.jar                      | None                                     |
	| LC    | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar             | None                                     |
	| LC    | redstoneflux             | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar          | None                                     |
	| LC    | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar             | None                                     |
	| LC    | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar             | None                                     |
	| LC    | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar             | None                                     |
	| LC    | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar             | None                                     |
	| LC    | antiqueatlasoverlay      | 1.2               | antiqueatlas-1.12.2-4.6.jar                      | None                                     |
	| LC    | aquaacrobatics           | 1.3.5             | AquaAcrobatics-v1.3.5-1.12.2.jar                 | None                                     |
	| LC    | astikorcarts             | 1.12.2-0.1.2.7    | astikorcarts-1.12.2-0.1.2.7.jar                  | None                                     |
	| LC    | atum                     | 2.0.20            | Atum-1.12.2-2.0.20.jar                           | None                                     |
	| LC    | autoreglib               | 1.3-32            | AutoRegLib-1.3-32.jar                            | None                                     |
	| LC    | bard_mania               | 0.15.0-alpha      | bard-mania_1.12.2-0.15.0-alpha.jar               | 999640c365a8443393a1a21df2c0ede9488400e9 |
	| LC    | bibliocraft              | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LC    | biomesoplenty            | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar    | None                                     |
	| LC    | cdm                      | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                           | None                                     |
	| LC    | bubble_burst             | 3.1               | BubbleBurst-3.1.jar                              | None                                     |
	| LC    | cdmcalculator            | 2.4               | CalculatorPlus-2.4+(0.4.0).jar                   | None                                     |
	| LC    | camera                   | 1.0.10            | camera-1.0.10.jar                                | None                                     |
	| LC    | cannibalism              | 5.6.5             | Cannibalism-5.6.5-1.12.2.jar                     | None                                     |
	| LC    | cfm                      | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                           | None                                     |
	| LC    | comforts                 | 1.4.1.2           | comforts-1.12.2-1.4.1.2.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | extendedrenderer         | v1.0              | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LC    | coroutil                 | 1.12.1-1.2.37     | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LC    | configmod                | v1.0              | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LC    | culinaryconstruct        | 1.3.4             | culinaryconstruct-1.3.4.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | galacticraftcore         | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar            | None                                     |
	| LC    | sereneseasons            | 1.2.18            | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
	| LC    | orelib                   | 3.6.0.1           | OreLib-1.12.2-3.6.0.1.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround                | 3.6.1.0           | DynamicSurroundings-1.12.2-3.6.1.0.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | emeraldexchange          | 1.2               | Emerald+Exchange-1.2.jar                         | None                                     |
	| LC    | erebus                   | 1.0.32            | Erebus-1.0.32.jar                                | None                                     |
	| LC    | exoticbirds              | 1.0               | Exotic+Birds+1.12.2-3.2.0.jar                    | None                                     |
	| LC    | minerva                  | 1.0.13            | minerva-library-1.0.13.jar                       | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LC    | extraalchemy             | 0.5.4             | extraalchemy-forge-1.12-build11-0.5.4.jar        | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LC    | galacticraftplanets      | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar        | None                                     |
	| LC    | mjrlegendslib            | 1.12.2-1.2.0      | MJRLegendsLib-1.12.2-1.2.0.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LC    | extraplanets             | 1.12.2-0.7.2      | ExtraPlanets-1.12.2-0.7.2.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LE    | extra_spells             | 1.1.4             | ExtraSpells-1.12.2-1.1.4.jar                     | None                                     |
	| L     | familiarfauna            | 1.0.11            | FamiliarFauna-1.12.2-1.0.11.jar                  | None                                     |
	| L     | llibrary                 | 1.7.20            | llibrary-1.7.20-1.12.2.jar                       | None                                     |
	| L     | fossil                   | 8.0.5             | fossilsarcheology-8.0.5.jar                      | None                                     |
	| L     | goodnightsleep           | 0.2.2             | good-nights-sleep-1.12.2-v0.2.2.jar              | None                                     |
	| L     | iceandfire               | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                      | None                                     |
	| L     | mca                      | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                   | None                                     |
	| L     | omca                     | 2.0.0             | omca-1.12.2-2.0.0.jar                            | None                                     |
	| L     | overpoweredarmorbar      | @VERSION@         | overloadedarmorbar-1.0.4g.jar                    | None                                     |
	| L     | potionfingers            | r1.0-8            | PotionFingers-r1.0-8.jar                         | None                                     |
	| L     | additionalstructures     | 2.3.1             | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| L     | t3s4ebw                  | 1.0               | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar     | None                                     |
	| L     | spyshop                  | 1.12.2-2.0        | ShopPlus-1.12.2-2.0.jar                          | None                                     |
	| L     | spartanshields           | 1.5.4             | SpartanShields-1.12.2-1.5.4.jar                  | None                                     |
	| L     | spartanweaponry          | beta 1.3.8        | SpartanWeaponry-1.12.2-beta-1.3.8.jar            | None                                     |
	| L     | strawgolem               | 1.3               | strawgolem-1.4.1.jar                             | None                                     |
	| L     | totemic                  | 1.12.2-0.11.6     | Totemic-1.12.2-0.11.6.jar                        | None                                     |
	| L     | twilightforest           | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar    | None                                     |
	| L     | uniquee                  | 1.9.0             | Unique+Enchantments+V1.12.2-1.9.jar              | None                                     |
	| L     | villagermarket           | 1.0.2             | villager-market-1.12.2-1.0.2.jar                 | None                                     |
	| L     | weather2                 | 1.12.1-2.6.12     | weather2-1.12.1-2.6.12.jar                       | None                                     |
	| L     | xercapaint               | 1.12.2-1.3        | xercapaint-1.12.2-1.3.jar                        | None                                     |
	| L     | zeherlib                 | 7.2.05            | zeherlib-1.12.2-7.2.05-universal.jar             | None                                     |
	| L     | betteranimalsplus        | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar               | None                                     |
	| L     | thebetweenlands          | 3.7.3             | TheBetweenlands-3.7.3-universal.jar              | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.042210-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.69' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
```

**Comment by Electroblob77** [comment]
Update extra spells to the latest version (1.2)
