### ISSUE TITLE
RenderMagicArrow Causing Crash

### ISSUE THREAD

**Issue by ongabonga** [Electroblob77/Wizardry#664]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/23/21 10:13 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: electroblob/wizardry/client/renderer/RenderMagicArrow
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: electroblob/wizardry/client/renderer/RenderMagicArrow
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: electroblob.wizardry.client.renderer.RenderMagicArrow
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 214834728 bytes (204 MB) / 1018167296 bytes (971 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version      | Source                                                   | Signature                                |
	|:----- |:------------------------ |:------------ |:-------------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2       | minecraft.jar                                            | None                                     |
	| LC    | mcp                      | 9.42         | minecraft.jar                                            | None                                     |
	| LC    | FML                      | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                    | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | placebo                  | 1.6.0        | Placebo-1.12.2-1.6.0.jar                                 | None                                     |
	| LC    | apotheosis               | 1.12.4       | Apotheosis-1.12.2-1.12.5.jar                             | None                                     |
	| LC    | jei                      | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar                                | None                                     |
	| LC    | appleskin                | 1.0.14       | AppleSkin-mc1.12-1.0.14.jar                              | None                                     |
	| LC    | baubles                  | 1.5.2        | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LC    | astralsorcery            | 1.10.19      | astralsorcery-1.12.2-1.10.19.jar                         | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LC    | astraladditions          | 1.12.2-1.0.0 | astraladditions-1.12.2-1.0.0.jar                         | None                                     |
	| LC    | biomesoplenty            | 7.0.1.2441   | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar            | None                                     |
	| LC    | chameleon                | 1.12-4.1.3   | Chameleon-1.12-4.1.3.jar                                 | None                                     |
	| LC    | customspawner            | 3.11.4       | CustomMobSpawner-3.11.5.jar                              | None                                     |
	| LC    | mocreatures              | 12.0.5       | DrZharks MoCreatures Mod-12.0.5.jar                      | None                                     |
	| LC    | ebwizardry               | 4.3.4        | ElectroblobsWizardry-4.3.4-MC1.12.2.jar                  | None                                     |
	| LC    | thaumcraft               | 6.1.BETA26   | Thaumcraft-1.12.2-6.1.BETA26.jar                         | None                                     |
	| LC    | enchantingwiththaumcraft | 1.3          | enchantingwiththaumcraft-1.3.jar                         | None                                     |
	| LE    | extra_spells             | 1.1.3        | ExtraSpells-1.12.2-1.1.3.jar                             | None                                     |
	| L     | gottschcore              | 1.14.0       | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.0.jar           | None                                     |
	| L     | ichunutil                | 7.2.2        | iChunUtil-1.12.2-7.2.2.jar                               | None                                     |
	| L     | hats                     | 7.1.1        | Hats-1.12.2-7.1.1.jar                                    | None                                     |
	| L     | mousetweaks              | 2.10         | MouseTweaks-2.10-mc1.12.2.jar                            | None                                     |
	| L     | llibrary                 | 1.7.20       | llibrary-1.7.20-1.12.2.jar                               | None                                     |
	| L     | mowziesmobs              | 1.5.7        | mowziesmobs-1.5.7.jar                                    | None                                     |
	| L     | t3s4ebw                  | 1.0          | SeedsForWizardry 1.0 For MC Forge 1.12.2.jar             | None                                     |
	| L     | storagedrawers           | 5.2.2        | StorageDrawers-1.12.2-5.4.2.jar                          | None                                     |
	| L     | tc6aspects4jei           | 0.0.2a       | tc6aspects4jei-0.0.2a.jar                                | None                                     |
	| L     | tcinventoryscan          | 2.0.10       | ThaumicInventoryScanning_1.12.2-2.0.10.jar               | None                                     |
	| L     | treasure2                | 1.16.1       | Treasure2-mc1.12.2-f14.23.5.2854-v1.16.1.jar             | None                                     |
	| L     | treasure2_mocreatures_lp | 1.0.0        | Treasure2MoCreaturesLP-mc1.12.2-f14.23.5.2854-v1.0.0.jar | None                                     |
	| L     | waddles                  | 0.6.0        | Waddles-1.12.2-0.6.0.jar                                 | None                                     |
	| L     | wizardryfates            | 1.0.2        | WizardryFates-1.0.2.jar                                  | None                                     |
	| L     | betteranimalsplus        | 9.0.1        | betteranimalsplus-1.12.2-9.0.1.jar                       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  
ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  shadows.ApotheosisTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.47' Renderer: 'NVIDIA GeForce 940M/PCIe/SSE2'

**Comment by Naigaru** [comment]
Update extra spells to 1.2.0 (latest version) as it is the only one compatible with your version of electroblobs wizardry - it’s not a bug

**Comment by Electroblob77** [comment]
Yes, this is caused by an outdated addon.
