### ISSUE TITLE
Crashes when using CodeChickenLib & Ancient Warfare 2

### ISSUE THREAD

**Issue by ERileyBaker** [Electroblob77/Wizardry#690]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: When starting up the game and using Wizardry, CodeChicken, and AW2, the game ALWAYS crashes

Other mods involved: Ancient Warfare 2, CodeChickenLib

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2021-07-08 20:39:08 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ancient Warfare Structures (ancientwarfarestructure)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.regex.Matcher.<init>(Matcher.java:225)
    at java.util.regex.Pattern.matcher(Pattern.java:1093)
    at net.minecraft.nbt.JsonToNBT.type(SourceFile:80)
    at net.minecraft.nbt.JsonToNBT.readTypedValue(SourceFile:75)
    at net.minecraft.nbt.JsonToNBT.readValue(SourceFile:164)
    at net.minecraft.nbt.JsonToNBT.readStruct(SourceFile:190)
    at net.minecraft.nbt.JsonToNBT.readValue(SourceFile:160)
    at net.minecraft.nbt.JsonToNBT.readStruct(SourceFile:190)
    at net.minecraft.nbt.JsonToNBT.readValue(SourceFile:160)
    at net.minecraft.nbt.JsonToNBT.readStruct(SourceFile:190)
    at net.minecraft.nbt.JsonToNBT.readSingleStruct(SourceFile:34)
    at net.minecraft.nbt.JsonToNBT.getTagFromJson(SourceFile:29)
    at net.shadowmage.ancientwarfare.structure.template.StructurePluginManager.readTag(StructurePluginManager.java:227)
    at net.shadowmage.ancientwarfare.structure.template.StructurePluginManager.getRule(StructurePluginManager.java:197)
    at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplateLines(TemplateParser.java:132)
    at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplate(TemplateParser.java:35)
    at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplate(TemplateLoader.java:128)
    at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.lambda$loadTemplatesFromSource$2(TemplateLoader.java:100)
    at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader$$Lambda$1417/1139387855.accept(Unknown Source)
    at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:66)
    at net.shadowmage.ancientwarfare.core.util.FileUtils.findFiles(FileUtils.java:24)
    at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplatesFromSource(TemplateLoader.java:85)
    at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplates(TemplateLoader.java:67)
    at net.shadowmage.ancientwarfare.structure.AncientWarfareStructure.postInit(AncientWarfareStructure.java:168)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 302131800 bytes (288 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 23 mods loaded, 23 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                       | Version           | Source                                        | Signature                                |
       |:----- |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
       | LCHIJ | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
       | LCHIJ | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | forge                    | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | antiqueatlas             | 4.6.3             | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
       | LCHIJ | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
       | LCHIJ | jei                      | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                     | None                                     |
       | LCHIJ | ebwizardry               | 4.3.4             | ElectroblobsWizardry-4.3.4-MC1.12.2.jar       | None                                     |
       | LCHIJ | ancientspellcraft        | 1.1.3             | ancientspellcraft-1.1.3.jar                   | None                                     |
       | LCHIJ | codechickenlib           | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJ | ancientwarfare           | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
       | LCHIJ | ancientwarfareautomation | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
       | LCHIJ | ancientwarfarenpc        | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
       | LCHIE | ancientwarfarestructure  | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
       | LCHI  | ancientwarfarevehicle    | 1.12.2-2.7.0.1038 | ancientwarfare-1.12.2-2.7.0.1038.jar          | None                                     |
       | LCHI  | antiqueatlasoverlay      | 1.2               | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
       | LCHI  | quark                    | r1.6-179          | Quark-r1.6-179.jar                            | None                                     |
       | LCHI  | autoreglib               | 1.3-32            | AutoRegLib-1.3-32.jar                         | None                                     |
       | LCHI  | harvestcraft             | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar               | None                                     |
       | LCHI  | roguelike                | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
       | LCHI  | vanillafix               | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCHI  | worldedit                | 6.1.10            | worldedit-forge-mc1.12.2-6.1.10-dist.jar      | None                                     |
       | LCHI  | llibrary                 | 1.7.20            | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
  Suspected Mods: Ancient Warfare Vehicles (ancientwarfarevehicle), Ancient Warfare Automation (ancientwarfareautomation), Ancient Warfare Structures (ancientwarfarestructure), Ancient Warfare NPCs (ancientwarfarenpc), Ancient Warfare Core (ancientwarfare)
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: GeForce GT 740/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, mod_resources, file/TCP_1.16b1.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by WinDanesz** [comment]
The error is clear, and it's not a mod issue. You don't have enough ram assigned to the game. If you have, AW2 you should assign at least 3Gb. 4 is recomended

**Comment by ERileyBaker** [comment]
i already assigned 4 gigs of ram to the installation via the mc launcher

**Comment by WinDanesz** [comment]
No, you only have 2Gb assigned

**Comment by ERileyBaker** [comment]
ohhh i think i know what happened

when i put in other mods afterwards the gigs reset to 2

ok now its 4
