### ISSUE TITLE
Server incompatibility

### ISSUE THREAD

**Issue by LemADEC** [Electroblob77/Wizardry#70]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Server

Issue details:
Console error about invalid reference to client side method when doing /allies:
```
[12:16:43] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'allies' for source EntityPlayerMP['xQnf'/38450, l='Twinkle', x=26.80, y=82.00, z=572.64]: java.lang.NoClassDefFoundEr
ror: net/minecraft/client/resources/I18n
java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
>       at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:164) ~[MinecraftCommandWrapper.class:1.12.2-2705-7.1.0-BETA-3409]
>       at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:145) ~[MinecraftCommandWrapper.class:1.12.2-2705-7.1.0-BETA-3409]
>       at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3409]
>       at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:329) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3409]
>       at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:1083) [dh.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:958) [pa.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:937) [pa.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3409]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) [hv$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
>       at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3409]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3972) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
>       at electroblob.wizardry.command.CommandViewAllies.execute(CommandViewAllies.java:105) ~[CommandViewAllies.class:?]
>       at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) ~[bj.class:?]
>       at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:160) ~[MinecraftCommandWrapper.class:1.12.2-2705-7.1.0-BETA-3409]
>       ... 21 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
>       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
>       at electroblob.wizardry.command.CommandViewAllies.execute(CommandViewAllies.java:105) ~[CommandViewAllies.class:?]
>       at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) ~[bj.class:?]
>       at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:160) ~[MinecraftCommandWrapper.class:1.12.2-2705-7.1.0-BETA-3409]
>       ... 21 more
```

Other mods involved:
none

Link to crash report (if applicable):
See above

**Comment by Electroblob77** [comment]
Ah yes, found the offending line. I have just fixed this in my local dev branch; it will be rolled out with the next update. Thanks for reporting.
