### ISSUE TITLE
(Intimidate spell) Ticking entity: Wizards frequently tick Minecolonies citizens

### ISSUE THREAD

**Issue by hoolatehip** [Electroblob77/Wizardry#732]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Singleplayer

Issue details: Various good and evil wizards (spawned in via Creative mode) fighting each other, some evil ones also fighting Minecolonies citizens. Game crashed. 

Other mods involved: Minecolonies

Crash report (if applicable): 

> java.lang.NullPointerException: Ticking entity
> 	at electroblob.wizardry.spell.Intimidate.runAway(Intimidate.java:106)
> 	at electroblob.wizardry.spell.Intimidate.onLivingUpdateEvent(Intimidate.java:136)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_412_Intimidate_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
> 	at net.minecraft.world.World.func_72866_a(World.java:1996)
> 	at net.minecraft.world.World.func_72870_g(World.java:1958)
> 	at net.minecraft.world.World.func_72939_s(World.java:1762)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by hoolatehip** [comment]
Happened a few more times. Looks like this bug is very common when wizards and citizens interact.
