### ISSUE TITLE
GuiWizardHandbook Crash with Forge 2859-2860

### ISSUE THREAD

**Issue by AzureDoom** [Electroblob77/Wizardry#764]
Minecraft version: 1.12.2 
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: Attempting to load the mod on 2860 results in a client crash, does not happen with 2847, however given the Log4J fixes done with 2860, it is irresponsible to still use 2847 with modpacks/servers. 

```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Electroblob's Wizardry (ebwizardry)
Caused by: java.lang.NullPointerException
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.getHandbookResource(GuiWizardHandbook.java:457)
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.loadHandbookFile(GuiWizardHandbook.java:400)
```

**Comment by Dancuo-Lohan** [comment]
Hi, yesterday my modpack worked well.
But today I've the same issue on the same version.

**Comment by WinDanesz** [comment]
And your server and the crashing client both has v2860?

**Comment by Dancuo-Lohan** [comment]
Sorry, I've mistaken that.

The server work fine with the mod.
But the client crash with this error :
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Electroblob's Wizardry (ebwizardry)
Caused by: java.lang.NullPointerException
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.getHandbookResource(GuiWizardHandbook.java:466)
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.loadHandbookFile(GuiWizardHandbook.java:409)
	at electroblob.wizardry.client.ClientProxy$$Lambda$302/1456038421.func_110549_a(Unknown Source)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at electroblob.wizardry.client.ClientProxy.registerResourceReloadListeners(ClientProxy.java:167)
	at electroblob.wizardry.Wizardry.preInit(Wizardry.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by WinDanesz** [comment]
That doesn't answer my question.
1) Forge version of the server?
2) Forge version if the client (that crashes)?
3) Full crash log, including the loaded mods
4) The log you just sent and the one sent by @AzureDoom can't be from the same wizardry version.. If you check the line numbers:

Yours:

Caused by: java.lang.NullPointerException
    at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.getHandbookResource(**GuiWizardHandbook.java:466**)
    at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.loadHandbookFile(**GuiWizardHandbook.java:409**)

___

AzureDoom's:

Caused by: java.lang.NullPointerException
    at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.getHandbookResource(**GuiWizardHandbook.java:457**)
    at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.loadHandbookFile(**GuiWizardHandbook.java:400**)

**Comment by Dancuo-Lohan** [comment]
1. The forge version of the server is a catserver version : `CatServer-5d66f2e-universal`

2. I've tested with forge `1.12.2 - 14.23.5.2860` and `1.12.2 - 14.23.5.2859` and have the same error.
And I've the last version of wizardry on Curseforge (`4.3.4`)

3. The full crash log :
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 1/26/22 11:20 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Electroblob's Wizardry (ebwizardry)
Caused by: java.lang.NullPointerException
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.getHandbookResource(GuiWizardHandbook.java:466)
	at electroblob.wizardry.client.gui.handbook.GuiWizardHandbook.loadHandbookFile(GuiWizardHandbook.java:409)
	at electroblob.wizardry.client.ClientProxy$$Lambda$302/662565333.func_110549_a(Unknown Source)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at electroblob.wizardry.client.ClientProxy.registerResourceReloadListeners(ClientProxy.java:167)
	at electroblob.wizardry.Wizardry.preInit(Wizardry.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1490573976 bytes (1421 MB) / 2147483648 bytes (2048 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                              | Version                  | Source                                        | Signature                                |
	|:----- |:------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                       | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCH   | mcp                             | 9.42                     | minecraft.jar                                 | None                                     |
	| LCH   | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                           | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | openmodscore                    | 0.12.2                   | minecraft.jar                                 | None                                     |
	| LCH   | tweakersconstruct               | 1.12.2-1.6.1             | tweakersconstruct-1.12.2-1.6.1.jar            | None                                     |
	| LCH   | appleskin                       | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCH   | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCH   | ctm                             | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCH   | chisel                          | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LCH   | twilightforest                  | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCH   | tconstruct                      | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCH   | conarm                          | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                    | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCH   | armoryexpansion                 | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCH   | armoryexpansion-custommaterials | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCH   | llibrary                        | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                      | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCH   | armoryexpansion-iceandfire      | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCH   | armoryexpansion-matteroverdrive | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCH   | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | bettercaves                     | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                  | None                                     |
	| LCH   | bettermineshafts                | 1.12.2-2.2.1             | BetterMineshaftsForge-1.12.2-2.2.1.jar        | None                                     |
	| LCH   | bibliocraft                     | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCH   | biomesoplenty                   | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCH   | champions                       | 1.12.2-1.0.11.8          | champions-1.12.2-1.0.11.8.jar                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | codechickenlib                  | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | collective                      | 2.26                     | collective-1.12.2-2.26.jar                    | None                                     |
	| LCH   | compot                          | 1.1                      | CombinedPotions-1.12-1.1.jar                  | None                                     |
	| LCH   | extendedrenderer                | v1.0                     | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCH   | coroutil                        | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCH   | configmod                       | v1.0                     | coroutil-1.12.1-1.2.37.jar                    | None                                     |
	| LCH   | customnpcs                      | 1.12                     | CustomNPCs_1.12.2-(05Jul20).jar               | None                                     |
	| LCH   | dawnoftimebuilder               | 1.0.7                    | dawnoftime_builder_edition-1.0.7.jar          | None                                     |
	| LCH   | dragonmounts                    | 1.12.2-1.6.3             | DragonMounts2-1.12.2-1.6.3.jar                | None                                     |
	| LCH   | eguilib                         | 0.1.2                    | eguilib-0.1.2.jar                             | None                                     |
	| LCE   | ebwizardry                      | 4.3.4                    | ElectroblobsWizardry-4.3.4-MC1.12.2.jar       | None                                     |
	| LC    | ftblib                          | 5.4.7.2                  | FTBLib-5.4.7.2.jar                            | None                                     |
	| LC    | ftbutilities                    | 5.4.1.130                | FTBUtilities-5.4.1.130.jar                    | None                                     |
	| LC    | itemfilters                     | 1.0.3.12                 | ItemFilters-1.0.3.12.jar                      | None                                     |
	| LC    | ftbquests                       | 1202.9.0.15              | FTBQuests-1202.9.0.15.jar                     | None                                     |
	| LC    | cfm                             | 6.3.1                    | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LC    | waila                           | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LC    | ironchest                       | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LC    | kinetic anti-cheat              | 12.2.2                   | kinetic_anti-cheat-12.2.2.jar                 | None                                     |
	| LC    | malisiscore                     | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LC    | malisisdoors                    | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LC    | metallurgy                      | 1.2.7                    | Metallurgy-4-Reforged-1.2.7.jar               | None                                     |
	| LC    | mowziesmobs                     | 1.5.6                    | mowziesmobs-1.5.6.jar                         | None                                     |
	| LC    | openmods                        | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | openblocks                      | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | harvestcraft                    | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar               | None                                     |
	| LC    | roguelike                       | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LC    | roughmobs                       | 2.0.0                    | roughmobs2-1.12.2_2.0.15.jar                  | None                                     |
	| LC    | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LC    | variedcommodities               | 1.12.2                   | VariedCommodities_1.12.2(21nov19).jar         | None                                     |
	| LC    | worldedit                       | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| LC    | zombieawareness                 | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar            | None                                     |
	| LC    | discordrpc                      | 1.3.3                    | discordrpc-1.3.3-1.12.jar                     | None                                     |
	| LC    | orelib                          | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | armoryexpansion-conarm          | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LC    | tweakersconstructpostload       | 1.12.2-1.6.1             | tweakersconstruct-1.12.2-1.6.1.jar            | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.32.05 27.20.11032.5001' Renderer: 'AMD Radeon(TM) Graphics'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13596 Compatibility Profile Context 20.10.32.05 27.20.11032.5001
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12
```

**Comment by WinDanesz** [comment]
What are your language settings @AzureDoom , @Dancuo-Lohan ? OS language and client language?

**Comment by WinDanesz** [comment]
To circle back to these issues, what language settings were you using?
