### ISSUE TITLE
greater fireball and other spells crash client but not server

### ISSUE THREAD

**Issue by eggmin249** [Electroblob77/Wizardry#783]
Minecraft version: 1.12.2 
Wizardry version: 4.3.5 
Environment: Server 

Issue details: the spells that don`t work are grey and say the element type is none when u try to cast it.It crashes client but the server continues to run  and the spell is still cast.Only the client using the spell crashes(other players who don`t cast the spell are fine) and it works fine on singleplayer 

Other mods involved :in crash report

Link to crash report (if applicable): ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.5.jar)
  CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.7B.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 2/23/22 7:24 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at electroblob.wizardry.spell.Spell.isEnabled(Spell.java:920)
	at electroblob.wizardry.WizardryEventHandler.onSpellCastPreEvent(WizardryEventHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_191_WizardryEventHandler_onSpellCastPreEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at electroblob.wizardry.item.ItemWand.canCast(ItemWand.java:453)
	at electroblob.wizardry.item.ItemWand.func_77659_a(ItemWand.java:377)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at electroblob.wizardry.spell.Spell.isEnabled(Spell.java:920)
	at electroblob.wizardry.WizardryEventHandler.onSpellCastPreEvent(WizardryEventHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_191_WizardryEventHandler_onSpellCastPreEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at electroblob.wizardry.item.ItemWand.canCast(ItemWand.java:453)
	at electroblob.wizardry.item.ItemWand.func_77659_a(ItemWand.java:377)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['eggary'/1781, l='MpServer', x=218.47, y=66.79, z=-252.53]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (217,64,-258), Chunk: (at 9,4,14 in 13,-17; contains blocks 208,0,-272 to 223,255,-257), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3496 game time, 3496 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntitySquid['Squid'/1793, l='MpServer', x=193.24, y=53.24, z=-229.56], EntitySquid['Squid'/1798, l='MpServer', x=162.06, y=62.40, z=-191.85], EntitySquid['Squid'/1801, l='MpServer', x=165.91, y=60.39, z=-191.49], EntityCreeper['Creeper'/2314, l='MpServer', x=266.50, y=19.00, z=-224.50], EntitySquid['Squid'/1803, l='MpServer', x=163.21, y=49.92, z=-252.73], EntitySquid['Squid'/1805, l='MpServer', x=234.92, y=47.17, z=-223.85], EntityWitch['Witch'/2318, l='MpServer', x=266.50, y=15.00, z=-221.50], EntitySquid['Squid'/1807, l='MpServer', x=235.05, y=47.14, z=-210.06], EntityZombie['Zombie'/2319, l='MpServer', x=271.00, y=15.00, z=-219.43], EntityZombie['Zombie'/2320, l='MpServer', x=269.80, y=17.00, z=-223.53], EntityGorgon['Gorgon'/19, l='MpServer', x=180.50, y=31.00, z=-244.50], EntityEnderman['Enderman'/2324, l='MpServer', x=277.50, y=13.00, z=-218.50], EntityCreeper['Creeper'/2326, l='MpServer', x=185.42, y=38.00, z=-247.42], EntitySquid['Squid'/1815, l='MpServer', x=212.04, y=51.50, z=-218.43], EntityCreeper['Creeper'/2327, l='MpServer', x=186.65, y=38.00, z=-248.70], EntityCreeper['Creeper'/2328, l='MpServer', x=184.52, y=38.00, z=-251.22], EntitySquid['Squid'/1817, l='MpServer', x=212.45, y=47.77, z=-221.24], EntityCreeper['Creeper'/2329, l='MpServer', x=184.50, y=38.00, z=-241.50], EntityAdvancedVampire['The powerful Bill'/32, l='MpServer', x=215.48, y=22.00, z=-199.77], EntityChickensChicken['Log Chicken'/33, l='MpServer', x=236.44, y=74.00, z=-284.50], EntityChickensChicken['Log Chicken'/34, l='MpServer', x=234.59, y=73.00, z=-284.19], EntityChickensChicken['Log Chicken'/35, l='MpServer', x=244.50, y=71.00, z=-280.89], EntityChickensChicken['Log Chicken'/36, l='MpServer', x=244.50, y=71.00, z=-281.33], EntityChickensChicken['Log Chicken'/37, l='MpServer', x=212.85, y=61.00, z=-262.50], EntityChickensChicken['Log Chicken'/38, l='MpServer', x=234.43, y=66.00, z=-271.50], EntityChickensChicken['Log Chicken'/39, l='MpServer', x=209.39, y=66.00, z=-250.53], EntityBat['Bat'/2343, l='MpServer', x=214.51, y=23.82, z=-203.29], EntityChickensChicken['Log Chicken'/40, l='MpServer', x=218.44, y=64.00, z=-260.79], EntityBat['Bat'/2347, l='MpServer', x=195.87, y=31.05, z=-244.68], EntityBat['Bat'/2348, l='MpServer', x=195.39, y=31.64, z=-250.49], EntitySquid['Squid'/1839, l='MpServer', x=224.71, y=43.09, z=-314.56], EntitySquid['Squid'/1841, l='MpServer', x=232.67, y=48.10, z=-312.05], EntitySquid['Squid'/1843, l='MpServer', x=159.44, y=55.56, z=-254.99], EntityBat['Bat'/2355, l='MpServer', x=179.82, y=41.04, z=-238.64], EntitySquid['Squid'/1848, l='MpServer', x=193.91, y=46.78, z=-230.55], EntitySquid['Squid'/1849, l='MpServer', x=197.44, y=45.53, z=-230.49], EntityPlayerSP['eggary'/1781, l='MpServer', x=218.47, y=66.79, z=-252.53], EntitySquid['Squid'/1854, l='MpServer', x=212.76, y=58.82, z=-190.28], EntitySquid['Squid'/1857, l='MpServer', x=206.85, y=57.56, z=-188.77], EntitySkeleton['Skeleton'/2115, l='MpServer', x=184.50, y=41.00, z=-238.50], EntitySpider['Spider'/2125, l='MpServer', x=182.50, y=31.00, z=-249.50], EntitySquid['Squid'/1871, l='MpServer', x=191.10, y=56.66, z=-196.31], EntitySquid['Squid'/1872, l='MpServer', x=185.61, y=57.25, z=-202.39], EntitySquid['Squid'/1873, l='MpServer', x=178.10, y=58.81, z=-198.18], EntityAbyssalZombie['Abyssal Zombie'/2133, l='MpServer', x=268.55, y=26.00, z=-196.24], EntitySquid['Squid'/1889, l='MpServer', x=182.49, y=46.00, z=-230.40], EntitySquid['Squid'/1890, l='MpServer', x=180.96, y=46.79, z=-233.46], EntityCreeper['Creeper'/2151, l='MpServer', x=233.50, y=27.00, z=-207.50], EntityBat['Bat'/1907, l='MpServer', x=280.24, y=23.03, z=-284.00], EntityItem['item.tile.gravel'/1656, l='MpServer', x=191.00, y=53.50, z=-248.13], EntityItem['item.tile.sand.default'/1657, l='MpServer', x=189.64, y=52.50, z=-250.78], EntityItem['item.tile.sand.default'/1659, l='MpServer', x=192.57, y=53.50, z=-244.88], EntityCreeper['Creeper'/1919, l='MpServer', x=279.50, y=19.00, z=-189.50], EntityBasicVampire['Vampire'/2185, l='MpServer', x=248.50, y=29.00, z=-248.50], EntityItem['item.tile.sand.default'/1679, l='MpServer', x=186.73, y=51.50, z=-252.88], EntityBat['Bat'/1936, l='MpServer', x=228.54, y=23.35, z=-255.47], EntityItem['item.tile.gravel'/1681, l='MpServer', x=190.26, y=51.50, z=-252.87], EntityItem['item.tile.sand.default'/1682, l='MpServer', x=189.59, y=53.50, z=-248.26], EntityItem['item.tile.sand.default'/1685, l='MpServer', x=194.80, y=53.50, z=-244.68], EntityItem['item.tile.gravel'/1687, l='MpServer', x=190.78, y=49.50, z=-256.13], EntityItem['item.tile.sand.default'/1688, l='MpServer', x=185.42, y=49.50, z=-256.55], EntityItem['item.tile.sand.default'/1689, l='MpServer', x=188.45, y=51.50, z=-252.13], EntityItem['item.tile.sand.default'/1690, l='MpServer', x=190.35, y=53.50, z=-248.60], EntityItem['item.tile.sand.default'/1694, l='MpServer', x=186.82, y=50.50, z=-254.68], EntityBat['Bat'/1955, l='MpServer', x=193.56, y=45.00, z=-242.75], EntityItem['item.item.string'/1700, l='MpServer', x=169.88, y=48.00, z=-250.96], EntityItem['item.item.string'/1701, l='MpServer', x=169.88, y=48.00, z=-253.81], EntityItem['item.item.string'/1703, l='MpServer', x=169.88, y=49.50, z=-252.69], EntityItem['item.tile.gravel'/1707, l='MpServer', x=191.21, y=40.50, z=-257.13], EntityItem['item.tile.gravel'/1708, l='MpServer', x=192.30, y=40.50, z=-257.18], EntityItem['item.tile.sand.default'/1709, l='MpServer', x=195.88, y=40.50, z=-244.20], EntityItem['item.item.string'/1712, l='MpServer', x=177.28, y=41.00, z=-246.24], EntityItem['item.item.string'/1713, l='MpServer', x=173.24, y=48.00, z=-236.88], EntityBat['Bat'/2228, l='MpServer', x=274.82, y=18.04, z=-234.63], EntityItem['item.tile.doublePlant.rose'/2231, l='MpServer', x=209.80, y=67.00, z=-260.05], EntityZombie['Zombie'/2232, l='MpServer', x=257.50, y=26.00, z=-297.50], EntityBat['Bat'/1992, l='MpServer', x=172.75, y=41.00, z=-241.48], EntityBat['Bat'/2249, l='MpServer', x=251.16, y=23.66, z=-232.72], EntityCreeper['Creeper'/2254, l='MpServer', x=175.50, y=38.00, z=-250.50], EntitySkeleton['Skeleton'/2255, l='MpServer', x=178.70, y=38.00, z=-242.70], EntitySkeleton['Skeleton'/2000, l='MpServer', x=193.23, y=41.00, z=-239.50], EntityCreeper['Creeper'/2256, l='MpServer', x=241.50, y=22.00, z=-307.50], EntitySkeleton['Skeleton'/2257, l='MpServer', x=233.50, y=14.00, z=-220.50], EntityCreeper['Creeper'/2003, l='MpServer', x=179.50, y=31.00, z=-260.50], EntitySpider['Spider'/2259, l='MpServer', x=235.50, y=14.00, z=-219.50], EntityCreeper['Creeper'/2261, l='MpServer', x=277.50, y=24.00, z=-239.50], EntitySkeleton['Skeleton'/2262, l='MpServer', x=273.50, y=24.00, z=-235.50], EntitySpider['Spider'/2266, l='MpServer', x=179.50, y=15.00, z=-192.50], EntityZombie['Zombie'/2272, l='MpServer', x=280.50, y=23.00, z=-196.50], EntityZombie['Zombie'/2273, l='MpServer', x=280.50, y=23.00, z=-198.50], EntityZombie['Zombie'/2274, l='MpServer', x=278.50, y=23.00, z=-196.50], EntitySkeleton['Skeleton'/2025, l='MpServer', x=176.75, y=38.00, z=-245.62], EntitySpider['Spider'/2026, l='MpServer', x=175.32, y=38.00, z=-243.86], EntityZombie['Zombie'/2286, l='MpServer', x=187.50, y=41.00, z=-236.50], EntityWitch['Witch'/2287, l='MpServer', x=247.50, y=29.00, z=-240.50], EntityItem['item.tile.doublePlant.syringa'/2290, l='MpServer', x=241.42, y=66.00, z=-270.81], EntityCreeper['Creeper'/2295, l='MpServer', x=267.50, y=18.00, z=-241.50], EntityBat['Bat'/2302, l='MpServer', x=155.03, y=14.75, z=-262.50], EntitySquid['Squid'/1791, l='MpServer', x=223.92, y=60.65, z=-218.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1645266080 bytes (1569 MB) / 2703753216 bytes (2578 MB) up to 5428477952 bytes (5177 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5824m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version           | Source                                        | Signature                                |
	|:------ |:--------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                   | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | reachfix              | 1.0.5             | minecraft.jar                                 | None                                     |
	| LCHIJA | obfuscate             | 0.4.2             | minecraft.jar                                 | None                                     |
	| LCHIJA | jei                   | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCHIJA | abyssalcraft          | 1.10.4            | AbyssalCraft-1.12.2-1.10.4.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | antiqueatlas          | 4.6.3             | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCHIJA | antiqueatlasoverlay   | 1.2               | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCHIJA | baubles               | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | chickens              | 6.1.0             | chickens-6.1.0.jar                            | None                                     |
	| LCHIJA | cqrepoured            | 2.6.7B            | Chocolate_Quest_Repoured-1.12.2-2.6.7B.jar    | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0             | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCHIJA | ebwizardry            | 4.3.5             | ElectroblobsWizardry-4.3.5-MC1.12.2.jar       | None                                     |
	| LCHIJA | fairylights           | 2.1.10            | fairylights-2.2.0-1.12.2.jar                  | None                                     |
	| LCHIJA | geckolib3             | 3.0.20            | geckolib-forge-1.12.2-3.0.21.jar              | None                                     |
	| LCHIJA | cgm                   | 0.15.3            | guns-0.15.3-1.12.2.jar                        | None                                     |
	| LCHIJA | hatchery              | 2.2.2             | hatchery-1.12.2-2.2.2.jar                     | None                                     |
	| LCHIJA | llibrary              | 1.7.20            | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire            | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | morechickens          | 3.2.0             | morechickens-1.12.2-3.2.0.jar                 | None                                     |
	| LCHIJA | patchouli             | 1.0-23.6          | Patchouli-1.0-23.6.jar                        | None                                     |
	| LCHIJA | redstoneflux          | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar       | None                                     |
	| LCHIJA | xat                   | 0.31.4            | Trinkets and Baubles-0.31.4.jar               | None                                     |
	| LCHIJA | spartanweaponry       | 1.4.1             | SpartanWeaponry-1.12.2-1.4.1.jar              | None                                     |
	| LCHIJA | spartanfire           | 0.08              | spartanfire-0.08.jar                          | None                                     |
	| LCHIJA | tektopia              | 1.1.0             | tektopia-1.1.0.jar                            | None                                     |
	| LCHIJA | tesla                 | 1.0.63            | Tesla-1.12.2-1.0.63.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | twilightforest        | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | tfspellpack           | 1.1.0             | TFSpellPack-1.1.0-MC1.12.2.jar                | None                                     |
	| LCHIJA | theoneprobe           | 1.4.28            | theoneprobe-1.12-1.4.28.jar                   | None                                     |
	| LCHIJA | vampiresneedumbrellas | 1.4               | VampiresNeedUmbrellas-1.12.2-1.5.jar          | None                                     |
	| LCHIJA | vampirism             | 1.6.2             | Vampirism-1.12.2-1.6.2.jar                    | None                                     |
	| LCHIJA | teamlapen-lib         | 1.6.2             | Vampirism-1.12.2-1.6.2.jar                    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ReachFixPlugin (ReachFix-1.12.2-1.0.5.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.7B.jar)
  team.cqr.cqrepoured.asm.CQRClassTransformer
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)

**Comment by eggmin249** [comment]
it was a multiplayer server

**Comment by eggmin249** [comment]
sorry for the inconvenience its bug with latest version
