### ISSUE TITLE
[Bug] Exception caught during firing event 

### ISSUE THREAD

**Issue by felipeleite5w** [Electroblob77/Wizardry#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Crash in my Minecraft Server, its 

### Expected behaviour

Exception caught during firing event net.minecraftforge.event.entity.living.LivingAttackEvent@664289c7:
java.lang.StackOverflowError
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
        at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:494) ~[?:1.8.0_312]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:146) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]
        at electroblob.wizardry.WizardryEventHandler.onLivingAttackEvent(WizardryEventHandler.java:196) ~[WizardryEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_WizardryEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.57]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.57]
        at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:303) ~[ForgeHooks.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848) ~[sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) ~[yg.class:?]

### Steps to reproduce

I dont know how to reproduce

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

latest for 1.7.10

### Minecraft version

1.7.10

### Forge version

1.7.10 latest

**Comment by felipeleite5w** [comment]
This error happened randonly

**Comment by WinDanesz** [comment]
Sorry, this version is no longer supported
